import { neon } from "@neondatabase/serverless";
import initialData from "../../data/db.json";
import { v4 as uuidv4 } from "uuid";

export type Program = {
  id: string;
  title: string;
  language: string;
  code: string;
};

export type Subject = {
  id: string;
  name: string;
  programs: Program[];
};

type SubjectProgramRow = {
  id: string;
  name: string;
  program_id: string | null;
  title: string | null;
  language: string | null;
  code: string | null;
};

let initialization: Promise<void> | undefined;

function getDatabase() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error(
      "DATABASE_URL is not configured. Connect a Postgres database to this Vercel project."
    );
  }

  return neon(connectionString);
}

async function initializeDatabase() {
  const sql = getDatabase();

  await sql`
    CREATE TABLE IF NOT EXISTS subjects (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      sort_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE
    )
  `;
  await sql`
    CREATE UNIQUE INDEX IF NOT EXISTS subjects_name_lower_idx
    ON subjects (LOWER(name))
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS programs (
      id TEXT PRIMARY KEY,
      subject_id TEXT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      language TEXT NOT NULL,
      code TEXT NOT NULL,
      sort_order BIGINT GENERATED ALWAYS AS IDENTITY
    )
  `;
  await sql`
    CREATE INDEX IF NOT EXISTS programs_subject_sort_idx
    ON programs (subject_id, sort_order)
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS app_metadata (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    )
  `;

  const seed = JSON.stringify(initialData.subjects);
  await sql`
    WITH seed_claim AS (
      INSERT INTO app_metadata (key, value)
      VALUES ('initial_data_seeded', 'true')
      ON CONFLICT (key) DO NOTHING
      RETURNING key
    ),
    seeded_subjects AS (
      INSERT INTO subjects (id, name)
      SELECT item.value->>'id', item.value->>'name'
      FROM seed_claim
      CROSS JOIN LATERAL jsonb_array_elements(${seed}::jsonb)
        WITH ORDINALITY AS item(value, subject_order)
      ORDER BY item.subject_order
      ON CONFLICT (id) DO NOTHING
      RETURNING id
    )
    INSERT INTO programs (id, subject_id, title, language, code)
    SELECT
      program.value->>'id',
      seeded_subjects.id,
      program.value->>'title',
      program.value->>'language',
      program.value->>'code'
    FROM seeded_subjects
    JOIN jsonb_array_elements(${seed}::jsonb) AS subject(value)
      ON subject.value->>'id' = seeded_subjects.id
    CROSS JOIN LATERAL jsonb_array_elements(subject.value->'programs')
      WITH ORDINALITY AS program(value, program_order)
    ORDER BY seeded_subjects.id, program.program_order
    ON CONFLICT (id) DO NOTHING
  `;
}

async function ensureInitialized() {
  if (!initialization) {
    initialization = initializeDatabase().catch((error: unknown) => {
      initialization = undefined;
      throw error;
    });
  }

  await initialization;
}

function groupSubjects(rows: SubjectProgramRow[]): Subject[] {
  const subjects = new Map<string, Subject>();

  for (const row of rows) {
    let subject = subjects.get(row.id);
    if (!subject) {
      subject = { id: row.id, name: row.name, programs: [] };
      subjects.set(row.id, subject);
    }

    if (
      row.program_id !== null &&
      row.title !== null &&
      row.language !== null &&
      row.code !== null
    ) {
      subject.programs.push({
        id: row.program_id,
        title: row.title,
        language: row.language,
        code: row.code,
      });
    }
  }

  return Array.from(subjects.values());
}

function getRow(value: unknown): Record<string, unknown> {
  if (typeof value !== "object" || value === null) {
    throw new Error("The database returned an invalid row.");
  }
  return value as Record<string, unknown>;
}

function getString(row: Record<string, unknown>, key: string): string {
  const value = row[key];
  if (typeof value !== "string") {
    throw new Error(`The database returned an invalid ${key} value.`);
  }
  return value;
}

function parseSubjectProgramRows(rows: unknown[]): SubjectProgramRow[] {
  return rows.map((value) => {
    const row = getRow(value);
    const programId = row.program_id;
    const title = row.title;
    const language = row.language;
    const code = row.code;

    if (
      (programId !== null && typeof programId !== "string") ||
      (title !== null && typeof title !== "string") ||
      (language !== null && typeof language !== "string") ||
      (code !== null && typeof code !== "string")
    ) {
      throw new Error("The database returned invalid program data.");
    }

    return {
      id: getString(row, "id"),
      name: getString(row, "name"),
      program_id: programId,
      title,
      language,
      code,
    };
  });
}

function parsePrograms(rows: unknown[]): Program[] {
  return rows.map((value) => {
    const row = getRow(value);
    return {
      id: getString(row, "id"),
      title: getString(row, "title"),
      language: getString(row, "language"),
      code: getString(row, "code"),
    };
  });
}

export async function getSubjects(): Promise<Subject[]> {
  await ensureInitialized();
  const sql = getDatabase();
  const rows = await sql`
    SELECT
      subjects.id,
      subjects.name,
      programs.id AS program_id,
      programs.title,
      programs.language,
      programs.code
    FROM subjects
    LEFT JOIN programs ON programs.subject_id = subjects.id
    ORDER BY subjects.sort_order, programs.sort_order
  `;
  return groupSubjects(parseSubjectProgramRows(rows));
}

export async function getSubject(id: string): Promise<Subject | undefined> {
  await ensureInitialized();
  const sql = getDatabase();
  const rows = await sql`
    SELECT
      subjects.id,
      subjects.name,
      programs.id AS program_id,
      programs.title,
      programs.language,
      programs.code
    FROM subjects
    LEFT JOIN programs ON programs.subject_id = subjects.id
    WHERE subjects.id = ${id}
    ORDER BY programs.sort_order
  `;
  return groupSubjects(parseSubjectProgramRows(rows))[0];
}

export async function getSubjectByName(
  name: string
): Promise<Subject | undefined> {
  await ensureInitialized();
  const sql = getDatabase();
  const rows = await sql`
    SELECT
      subjects.id,
      subjects.name,
      programs.id AS program_id,
      programs.title,
      programs.language,
      programs.code
    FROM subjects
    LEFT JOIN programs ON programs.subject_id = subjects.id
    WHERE LOWER(subjects.name) = LOWER(${name.trim()})
    ORDER BY programs.sort_order
  `;
  return groupSubjects(parseSubjectProgramRows(rows))[0];
}

export async function createSubject(name: string): Promise<Subject> {
  await ensureInitialized();
  const sql = getDatabase();
  const id = uuidv4();
  const [subject] = await sql`
    INSERT INTO subjects (id, name)
    VALUES (${id}, ${name.trim()})
    RETURNING id, name
  `;

  if (!subject) {
    throw new Error("The database did not return the created subject.");
  }
  const row = getRow(subject);
  return {
    id: getString(row, "id"),
    name: getString(row, "name"),
    programs: [],
  };
}

export async function deleteSubject(id: string): Promise<boolean> {
  await ensureInitialized();
  const sql = getDatabase();
  const deleted = await sql`
    DELETE FROM subjects WHERE id = ${id} RETURNING id
  `;
  return deleted.length > 0;
}

export async function addProgram(
  subjectId: string,
  title: string,
  language: string,
  code: string
): Promise<Program | null> {
  await ensureInitialized();
  const sql = getDatabase();
  const [program] = await sql`
    INSERT INTO programs (id, subject_id, title, language, code)
    SELECT ${uuidv4()}, id, ${title.trim()}, ${language.trim()}, ${code}
    FROM subjects
    WHERE id = ${subjectId}
    RETURNING id, title, language, code
  `;
  return program ? parsePrograms([program])[0] : null;
}

export async function updateProgram(
  subjectId: string,
  programId: string,
  title: string,
  language: string,
  code: string
): Promise<Program | null> {
  await ensureInitialized();
  const sql = getDatabase();
  const [program] = await sql`
    UPDATE programs
    SET title = ${title.trim()}, language = ${language.trim()}, code = ${code}
    WHERE subject_id = ${subjectId} AND id = ${programId}
    RETURNING id, title, language, code
  `;
  return program ? parsePrograms([program])[0] : null;
}

export async function deleteProgram(
  subjectId: string,
  programId: string
): Promise<boolean> {
  await ensureInitialized();
  const sql = getDatabase();
  const deleted = await sql`
    DELETE FROM programs
    WHERE subject_id = ${subjectId} AND id = ${programId}
    RETURNING id
  `;
  return deleted.length > 0;
}

export async function getProgram(
  subjectId: string,
  programId: string
): Promise<Program | null> {
  await ensureInitialized();
  const sql = getDatabase();
  const [program] = await sql`
    SELECT id, title, language, code
    FROM programs
    WHERE subject_id = ${subjectId} AND id = ${programId}
  `;
  return program ? parsePrograms([program])[0] : null;
}
